name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  publish_docker_image:
    name: Publish Docker Image to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker image to GHCR
        env:
          IMG_REPO: ${{ env.IMAGE_NAME }}
          IMG_TAG: ${{ join(fromJSON(steps.meta.outputs.json).tags, ' ') }}
          PUSH_REPO: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        run: |
          yes | make docker-build
